name: str()
kubeVersion: str()
apiVersion: str()
appVersion: any(str(), num())
version: str(required=True)
upstream_version: any(str(), num(), required=False)
description: str()
type: str(required=False)
home: str(required=False)
icon: str(required=False)
sources: list(str(), required=False)
dependencies: list(include('dependency'), required=False)
deprecated: bool(required=False)
engine: str(required=False)
condition: str(required=False)
keywords: list(str(), required=False)
tags: str(required=False)
maintainers: list(include('maintainer'))
annotations: map(str(), str(), required=False)
---
maintainer:
  name: str()
  email: str(required=False)
---
dependency:
  name: str()
  repository: str()
  version: str()
  condition: str(required=False)
  tags: list(str(), required=False)
  import-values: any(list(str()), list(include('import-value')), required=False)
  enabled: bool(required=False)
  alias: str(required=False)
---
import-value:
  child: str()
  parent: str()