# https://taskfile.dev

version: '3'

vars:
  CHART: base-chart
  K8S_VERSION: 1.32.0

tasks:
  lint:
    cmds:
      - |
        ct lint --config ./ct/config.yaml \
        --lint-conf ./ct/lint.yaml \
        --charts {{ .CHART }} --debug
  
  unit:
    cmds: #TODO Kyverno CLI
  
  schema:
    cmds:
      - |
        helm template {{.CHART }} | kubeconform --summary \
        --strict --ignore-missing-schemas --kubernetes-version {{ .K8S_VERSION }}
  
  dry-run:
    preconditions:
      - kind create cluster --name helm-qg --config ./kind/cluster.yaml
    cmds:
      - helm install "{{ .CHART }}" --dry-run=server
  